# Azure Pipeline for Deploying Bicep Infrastructure
# This pipeline deploys the resource group, compute gallery, and VM resources using tested Bicep files.

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'development' 
  location: 'canadacentral'
  resourceGroupName: 'dcacerg'
  galleryName: 'dcacecg'
  imageDefinitionName: 'dwinlatest'
  vmName: 'dcacevm1'
  vnetName: 'dcacevnet'
  subnetName: 'dcacesubnet'
  keyVaultName: 'dcacekv' 
  
stages:
- stage: DeployInfra
  displayName: 'Deploy Infrastructure'
  jobs:
  - job: DeployRG
    displayName: 'Deploy Resource Group'
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Resource Group Bicep'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment sub create \
            --location $(location) \
            --template-file infra/create-rg.bicep \
            --parameters resourceGroupName=$(resourceGroupName)

  - job: DeployGallery
    displayName: 'Deploy Compute Gallery, VNet, NSG'
    dependsOn: DeployRG
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy Compute Gallery Bicep'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file infra/compute-gallery.bicep \
            --parameters galleryName=$(galleryName) keyVaultName=$(keyVaultName)

  - job: SetAdminPassword
    displayName: 'Generate and Store Admin Password in Key Vault'
    dependsOn: DeployGallery
    steps:
    - task: AzureCLI@2
      displayName: 'Generating key vault secret'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          $secretId = [System.Web.Security.Membership]::GeneratePassword(20,3)
          az keyvault secret set --vault-name $(keyVaultName) --name "secretId" --value $secretId
          echo "##vso[task.setvariable variable=secretId;issecret=true]$secretId"

  - job: DeployVM
    displayName: 'Deploy VM from Marketplace Image'
    dependsOn: SetAdminPassword
    steps:
    - task: AzureCLI@2
      displayName: 'Deploy VM Bicep'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'ps'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az deployment group create \
            --resource-group $(resourceGroupName) \
            --template-file infra/vm-from-store.bicep \
            --parameters @infra/vm.parameters.json \
            --parameters adminPasswordSecretName=secretId keyVaultName=$(keyVaultName)

# Secrets (adminUsername, adminPassword) should be set as pipeline variables or Azure Key Vault references.
# Update 'azureSubscription' with your Azure service connection name.
# Adjust parameters as needed for your environment.
